Repository agamjotsingh18/pollitup, pull requests merged in 2023-06, with the labels that each got.

#144 Connect Create Pole form to Firebase Backend, closes pr #112
  src/lib/db.js
  src/pages/create.jsx
Labels: GSSoC23

#173 Meta tags added
  public/index.html
Labels: Level1, GSSoC23

#229 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: level2, gssoc23
